In [2]:
import numpy as np

#Input
x = np.array([[0,1],[0,0],[1,1],[1,0]])

#Output
y = np.array([[1],[0],[0],[1]])

#Weights
w1 = np.random.randn(2,2)
w2 = np.random.randn(2,1)

#Biases
b1 = np.random.randn(1,2)
b2 = np.random.randn(1,1)


# Learning rate
lr = 0.1

# Iterations
loops = 30000

#Sigmoid Function
def sigmoid (x): 
    return 1/(1 + np.exp(-x))

#Sigmoid Derivative
def s_deriv(x):
    return x * (1 - x)

#Training
for i in range(loops):
    
    #Forward Propagation
    layer1 = x
    z1 = np.dot(layer1, w1) + b1
    
    layer2 = sigmoid(z1)
    z2 = np.dot(layer2, w2) + b2
    output = sigmoid(z2)
    
    #Back Propagation
    error = y - output
    d_output = error * s_deriv(output)
    d_hidden_layer = np.dot(d_output, w2.T) * s_deriv(layer2)
    
    w2 += lr * np.dot(layer2.T, d_output)
    b2 += lr * d_output.sum(axis=0)

    w1 += lr * np.dot(layer1.T, d_hidden_layer)
    b1 += lr * d_hidden_layer.sum(axis=0)
    
    

    
print("Inputs: \n", x)
print("Weights 1: \n", w1, "\nWeights 2: \n", w2)
print("Bias 1: \n", b1, "\nBias 2: \n", b2)
print("Output: \n", output)

Inputs: 
 [[0 1]
 [0 0]
 [1 1]
 [1 0]]
Weights 1: 
 [[-5.84092747 -4.8260378 ]
 [-5.83538995 -4.8244341 ]] 
Weights 2: 
 [[-9.59224367]
 [ 9.21275592]]
Bias 1: 
 [[2.33453766 7.19103264]] 
Bias 2: 
 [[-4.32683969]]
Output: 
 [[0.97843568]
 [0.02050794]
 [0.02654147]
 [0.978443  ]]
